# Genre.create!(name: "IT")
# Genre.create!(name: "音楽")
# Genre.create!(name: "スポーツ")
# Genre.create!(name: "教育")

# Term.create!(name: "シンコペーション", user_id: 1, genre_id: 2)
# Term.create!(name: "デッド", user_id: 2, genre_id: 2)
# Term.create!(name: "プリプロ", user_id: 3, genre_id: 2)
# Term.create!(name: "マスタリング", user_id: 1, genre_id: 2)

# Tag.create!(name: "ITタグ1", user_id: 1, genre_id: 1)
# Tag.create!(name: "ITタグ2", user_id: 2, genre_id: 1)
# Tag.create!(name: "ITタグ3", user_id: 3, genre_id: 1)
# Tag.create!(name: "ITタグ4", user_id: 5, genre_id: 1)
# Tag.create!(name: "ITタグ5", user_id: 5, genre_id: 1)
# Tag.create!(name: "音楽タグ1", user_id: 1, genre_id: 2)
# Tag.create!(name: "音楽タグ2", user_id: 2, genre_id: 2)
# Tag.create!(name: "音楽タグ3", user_id: 3, genre_id: 2)
# Tag.create!(name: "音楽タグ4", user_id: 5, genre_id: 2)
# Tag.create!(name: "音楽タグ5", user_id: 2, genre_id: 2)
# Tag.create!(name: "スポーツタグ1", user_id: 1, genre_id: 3)
# Tag.create!(name: "スポーツタグ2", user_id: 2, genre_id: 3)
# Tag.create!(name: "スポーツタグ3", user_id: 3, genre_id: 3)
# Tag.create!(name: "スポーツタグ4", user_id: 5, genre_id: 3)
# Tag.create!(name: "スポーツタグ5", user_id: 1, genre_id: 3)
# Tag.create!(name: "教育タグ1", user_id: 1, genre_id: 4)
# Tag.create!(name: "教育タグ2", user_id: 2, genre_id: 4)
# Tag.create!(name: "教育タグ3", user_id: 3, genre_id: 4)
# Tag.create!(name: "教育タグ4", user_id: 5, genre_id: 4)
# Tag.create!(name: "教育タグ5", user_id: 1, genre_id: 4)
