# Genre.create!(name: "IT")
# Genre.create!(name: "音楽")
# Genre.create!(name: "スポーツ")
# Genre.create!(name: "教育")

# Term.create!(name: "シンコペーション", user_id: 1, genre_id: 2)
# Term.create!(name: "デッド", user_id: 2, genre_id: 2)
# Term.create!(name: "プリプロ", user_id: 3, genre_id: 2)
# Term.create!(name: "マスタリング", user_id: 1, genre_id: 2)

# Tag.create!(name: "1aa", user_id: 1, genre_id: 1)
# Tag.create!(name: "2aa", user_id: 2, genre_id: 1)
# Tag.create!(name: "3aa", user_id: 3, genre_id: 1)
# Tag.create!(name: "4aa", user_id: 5, genre_id: 1)
# Tag.create!(name: "4aa", user_id: 5, genre_id: 1)
# Tag.create!(name: "1aa", user_id: 1, genre_id: 2)
# Tag.create!(name: "2aa", user_id: 2, genre_id: 2)
# Tag.create!(name: "3aa", user_id: 3, genre_id: 2)
# Tag.create!(name: "4aa", user_id: 5, genre_id: 2)
# Tag.create!(name: "2aa", user_id: 2, genre_id: 2)
# Tag.create!(name: "1aa", user_id: 1, genre_id: 3)
# Tag.create!(name: "2aa", user_id: 2, genre_id: 3)
# Tag.create!(name: "3aa", user_id: 3, genre_id: 3)
# Tag.create!(name: "4aa", user_id: 5, genre_id: 3)
# Tag.create!(name: "1aa", user_id: 1, genre_id: 3)
# Tag.create!(name: "1aa", user_id: 1, genre_id: 4)
# Tag.create!(name: "2aa", user_id: 2, genre_id: 4)
# Tag.create!(name: "3aa", user_id: 3, genre_id: 4)
# Tag.create!(name: "4aa", user_id: 5, genre_id: 4)
# Tag.create!(name: "1aa", user_id: 1, genre_id: 4)
